---
Name: lasysizes
---
Image:
  extensions:
    - LazySizesImageExtension
Controller:
  extensions:
    - LazySizesControllerExtension
LazySizesImageExtension:
  default_method: SetWidth
  default_size: 800x600
  lqip_size: 220
  # pattern could be: noscript, simple, lqip
  pattern: 'simple'
  js_path: 'lazysizes/javascript'
  always_load: true
  sets:
    default: [320,640,960,1280]